apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-cbc
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: kind/challenge:ea90f220f17404eb589ff4bd7ba5047d9a1371db81481044596c520aadc0fa06
